//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COWE.PacketsTestDatabaseInitialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchInterval
    {
        public int BatchIntervalId { get; set; }
        public int CaptureBatchId { get; set; }
        public int IntervalNumber { get; set; }
        public int PacketCount { get; set; }
    
        public virtual CaptureBatch CaptureBatch { get; set; }
    }
}
