//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COWE.PacketsTestDatabaseInitialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapturePacket
    {
        public int CapturePacketId { get; set; }
        public int CaptureBatchId { get; set; }
        public int PacketNumber { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Marked { get; set; }
    
        public virtual CaptureBatch CaptureBatch { get; set; }
    }
}
