//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COWE.PacketsTestDatabaseInitialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumulativeInterval
    {
        public int CumulativeIntervalId { get; set; }
        public int CumulativeIntervalNumber { get; set; }
        public int PacketCount { get; set; }
        public bool Marked { get; set; }
    }
}
