//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COWE.PacketsTestDatabaseInitialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayStatistic
    {
        public int DisplayStatisticId { get; set; }
        public int IntervalCount { get; set; }
        public int TrimmedIntervalCount { get; set; }
        public decimal MeanPacketsPerInterval { get; set; }
        public decimal StandardDeviation { get; set; }
        public int MinPacketsPerInterval { get; set; }
        public int MaxPacketsPerInterval { get; set; }
        public decimal MeanOfMeans { get; set; }
        public decimal MeanOfMeansStandardDeviation { get; set; }
        public bool Marked { get; set; }
        public int BatchType { get; set; }
    }
}
