//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COWE.PacketsTestDatabaseInitialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class HypothesisTest
    {
        public int HypothesisTestId { get; set; }
        public decimal MeanOfMeansVariance { get; set; }
        public decimal MeansVarianceStandardDeviation { get; set; }
        public decimal KsStatistic { get; set; }
        public decimal MaxCpdVariance { get; set; }
        public bool MeansTestResult { get; set; }
        public bool KsTestResult { get; set; }
        public bool HasValues { get; set; }
    }
}
