//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COWE.PacketsTestDatabaseInitialization
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PacketsTestEntities : DbContext
    {
        public PacketsTestEntities()
            : base("name=PacketsTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchInterval> BatchIntervals { get; set; }
        public virtual DbSet<CaptureBatch> CaptureBatches { get; set; }
        public virtual DbSet<CapturePacket> CapturePackets { get; set; }
        public virtual DbSet<CumulativeHistogram> CumulativeHistograms { get; set; }
        public virtual DbSet<CumulativeInterval> CumulativeIntervals { get; set; }
        public virtual DbSet<CumulativeProbabilityDistribution> CumulativeProbabilityDistributions { get; set; }
        public virtual DbSet<DisplayStatistic> DisplayStatistics { get; set; }
        public virtual DbSet<HypothesisTest> HypothesisTests { get; set; }
        public virtual DbSet<SingleHistogram> SingleHistograms { get; set; }
    
        public virtual int TruncateAllIntervalTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateAllIntervalTables");
        }
    
        public virtual int TruncateAllTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateAllTables");
        }
    }
}
