//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(COWE.PacketsTestDatabaseInitialization.PacketsTestEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets1bd3a0381aeab51d5cf0ba1530ae3117f230981af6c3992780c40942049ac662))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySets1bd3a0381aeab51d5cf0ba1530ae3117f230981af6c3992780c40942049ac662 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "1bd3a0381aeab51d5cf0ba1530ae3117f230981af6c3992780c40942049ac662"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "COWEPacketsTestModelStoreContainer.BatchInterval")
            {
                return GetView0();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.CaptureBatch")
            {
                return GetView1();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.CapturePacket")
            {
                return GetView2();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.SingleHistogram")
            {
                return GetView3();
            }

            if (extentName == "PacketsTestEntities.BatchIntervals")
            {
                return GetView4();
            }

            if (extentName == "PacketsTestEntities.CaptureBatches")
            {
                return GetView5();
            }

            if (extentName == "PacketsTestEntities.CapturePackets")
            {
                return GetView6();
            }

            if (extentName == "PacketsTestEntities.SingleHistograms")
            {
                return GetView7();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.CumulativeHistogram")
            {
                return GetView8();
            }

            if (extentName == "PacketsTestEntities.CumulativeHistograms")
            {
                return GetView9();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.CumulativeInterval")
            {
                return GetView10();
            }

            if (extentName == "PacketsTestEntities.CumulativeIntervals")
            {
                return GetView11();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.CumulativeProbabilityDistribution")
            {
                return GetView12();
            }

            if (extentName == "PacketsTestEntities.CumulativeProbabilityDistributions")
            {
                return GetView13();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.DisplayStatistic")
            {
                return GetView14();
            }

            if (extentName == "PacketsTestEntities.DisplayStatistics")
            {
                return GetView15();
            }

            if (extentName == "COWEPacketsTestModelStoreContainer.HypothesisTest")
            {
                return GetView16();
            }

            if (extentName == "PacketsTestEntities.HypothesisTests")
            {
                return GetView17();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.BatchInterval.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BatchInterval
        [COWE.PacketsTestModel.Store.BatchInterval](T1.BatchInterval_BatchIntervalId, T1.BatchInterval_CaptureBatchId, T1.BatchInterval_IntervalNumber, T1.BatchInterval_PacketCount)
    FROM (
        SELECT 
            T.BatchIntervalId AS BatchInterval_BatchIntervalId, 
            T.CaptureBatchId AS BatchInterval_CaptureBatchId, 
            T.IntervalNumber AS BatchInterval_IntervalNumber, 
            T.PacketCount AS BatchInterval_PacketCount, 
            True AS _from0
        FROM PacketsTestEntities.BatchIntervals AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.CaptureBatch.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CaptureBatch
        [COWE.PacketsTestModel.Store.CaptureBatch](T1.CaptureBatch_CaptureBatchId, T1.CaptureBatch_FileName, T1.CaptureBatch_Marked, T1.CaptureBatch_Mean, T1.CaptureBatch_TrimmedMean, T1.CaptureBatch_Parsed, T1.CaptureBatch_SingleStatistics, T1.CaptureBatch_CumulativeStatistics)
    FROM (
        SELECT 
            T.CaptureBatchId AS CaptureBatch_CaptureBatchId, 
            T.FileName AS CaptureBatch_FileName, 
            T.Marked AS CaptureBatch_Marked, 
            T.Mean AS CaptureBatch_Mean, 
            T.TrimmedMean AS CaptureBatch_TrimmedMean, 
            T.Parsed AS CaptureBatch_Parsed, 
            T.SingleStatistics AS CaptureBatch_SingleStatistics, 
            T.CumulativeStatistics AS CaptureBatch_CumulativeStatistics, 
            True AS _from0
        FROM PacketsTestEntities.CaptureBatches AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.CapturePacket.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CapturePacket
        [COWE.PacketsTestModel.Store.CapturePacket](T1.CapturePacket_CapturePacketId, T1.CapturePacket_CaptureBatchId, T1.CapturePacket_PacketNumber, T1.CapturePacket_TimeStamp, T1.CapturePacket_Marked)
    FROM (
        SELECT 
            T.CapturePacketId AS CapturePacket_CapturePacketId, 
            T.CaptureBatchId AS CapturePacket_CaptureBatchId, 
            T.PacketNumber AS CapturePacket_PacketNumber, 
            T.TimeStamp AS CapturePacket_TimeStamp, 
            T.Marked AS CapturePacket_Marked, 
            True AS _from0
        FROM PacketsTestEntities.CapturePackets AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.SingleHistogram.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SingleHistogram
        [COWE.PacketsTestModel.Store.SingleHistogram](T1.SingleHistogram_SingleHistogramId, T1.SingleHistogram_CaptureBatchId, T1.SingleHistogram_Interval, T1.SingleHistogram_Probability, T1.SingleHistogram_CaptureState)
    FROM (
        SELECT 
            T.SingleHistogramId AS SingleHistogram_SingleHistogramId, 
            T.CaptureBatchId AS SingleHistogram_CaptureBatchId, 
            T.Interval AS SingleHistogram_Interval, 
            T.Probability AS SingleHistogram_Probability, 
            T.CaptureState AS SingleHistogram_CaptureState, 
            True AS _from0
        FROM PacketsTestEntities.SingleHistograms AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.BatchIntervals.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BatchIntervals
        [COWE.PacketsTestModel.BatchInterval](T1.BatchInterval_BatchIntervalId, T1.BatchInterval_CaptureBatchId, T1.BatchInterval_IntervalNumber, T1.BatchInterval_PacketCount)
    FROM (
        SELECT 
            T.BatchIntervalId AS BatchInterval_BatchIntervalId, 
            T.CaptureBatchId AS BatchInterval_CaptureBatchId, 
            T.IntervalNumber AS BatchInterval_IntervalNumber, 
            T.PacketCount AS BatchInterval_PacketCount, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.BatchInterval AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.CaptureBatches.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CaptureBatches
        [COWE.PacketsTestModel.CaptureBatch](T1.CaptureBatch_CaptureBatchId, T1.CaptureBatch_FileName, T1.CaptureBatch_Marked, T1.CaptureBatch_Mean, T1.CaptureBatch_TrimmedMean, T1.CaptureBatch_Parsed, T1.CaptureBatch_SingleStatistics, T1.CaptureBatch_CumulativeStatistics)
    FROM (
        SELECT 
            T.CaptureBatchId AS CaptureBatch_CaptureBatchId, 
            T.FileName AS CaptureBatch_FileName, 
            T.Marked AS CaptureBatch_Marked, 
            T.Mean AS CaptureBatch_Mean, 
            T.TrimmedMean AS CaptureBatch_TrimmedMean, 
            T.Parsed AS CaptureBatch_Parsed, 
            T.SingleStatistics AS CaptureBatch_SingleStatistics, 
            T.CumulativeStatistics AS CaptureBatch_CumulativeStatistics, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.CaptureBatch AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.CapturePackets.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CapturePackets
        [COWE.PacketsTestModel.CapturePacket](T1.CapturePacket_CapturePacketId, T1.CapturePacket_CaptureBatchId, T1.CapturePacket_PacketNumber, T1.CapturePacket_TimeStamp, T1.CapturePacket_Marked)
    FROM (
        SELECT 
            T.CapturePacketId AS CapturePacket_CapturePacketId, 
            T.CaptureBatchId AS CapturePacket_CaptureBatchId, 
            T.PacketNumber AS CapturePacket_PacketNumber, 
            T.TimeStamp AS CapturePacket_TimeStamp, 
            T.Marked AS CapturePacket_Marked, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.CapturePacket AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.SingleHistograms.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SingleHistograms
        [COWE.PacketsTestModel.SingleHistogram](T1.SingleHistogram_SingleHistogramId, T1.SingleHistogram_CaptureBatchId, T1.SingleHistogram_Interval, T1.SingleHistogram_Probability, T1.SingleHistogram_CaptureState)
    FROM (
        SELECT 
            T.SingleHistogramId AS SingleHistogram_SingleHistogramId, 
            T.CaptureBatchId AS SingleHistogram_CaptureBatchId, 
            T.Interval AS SingleHistogram_Interval, 
            T.Probability AS SingleHistogram_Probability, 
            T.CaptureState AS SingleHistogram_CaptureState, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.SingleHistogram AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.CumulativeHistogram.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CumulativeHistogram
        [COWE.PacketsTestModel.Store.CumulativeHistogram](T1.CumulativeHistogram_CumulativeHistogramId, T1.CumulativeHistogram_Interval, T1.CumulativeHistogram_Probability, T1.CumulativeHistogram_CaptureState)
    FROM (
        SELECT 
            T.CumulativeHistogramId AS CumulativeHistogram_CumulativeHistogramId, 
            T.Interval AS CumulativeHistogram_Interval, 
            T.Probability AS CumulativeHistogram_Probability, 
            T.CaptureState AS CumulativeHistogram_CaptureState, 
            True AS _from0
        FROM PacketsTestEntities.CumulativeHistograms AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.CumulativeHistograms.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CumulativeHistograms
        [COWE.PacketsTestModel.CumulativeHistogram](T1.CumulativeHistogram_CumulativeHistogramId, T1.CumulativeHistogram_Interval, T1.CumulativeHistogram_Probability, T1.CumulativeHistogram_CaptureState)
    FROM (
        SELECT 
            T.CumulativeHistogramId AS CumulativeHistogram_CumulativeHistogramId, 
            T.Interval AS CumulativeHistogram_Interval, 
            T.Probability AS CumulativeHistogram_Probability, 
            T.CaptureState AS CumulativeHistogram_CaptureState, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.CumulativeHistogram AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.CumulativeInterval.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CumulativeInterval
        [COWE.PacketsTestModel.Store.CumulativeInterval](T1.CumulativeInterval_CumulativeIntervalId, T1.CumulativeInterval_CumulativeIntervalNumber, T1.CumulativeInterval_PacketCount, T1.CumulativeInterval_Marked)
    FROM (
        SELECT 
            T.CumulativeIntervalId AS CumulativeInterval_CumulativeIntervalId, 
            T.CumulativeIntervalNumber AS CumulativeInterval_CumulativeIntervalNumber, 
            T.PacketCount AS CumulativeInterval_PacketCount, 
            T.Marked AS CumulativeInterval_Marked, 
            True AS _from0
        FROM PacketsTestEntities.CumulativeIntervals AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.CumulativeIntervals.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CumulativeIntervals
        [COWE.PacketsTestModel.CumulativeInterval](T1.CumulativeInterval_CumulativeIntervalId, T1.CumulativeInterval_CumulativeIntervalNumber, T1.CumulativeInterval_PacketCount, T1.CumulativeInterval_Marked)
    FROM (
        SELECT 
            T.CumulativeIntervalId AS CumulativeInterval_CumulativeIntervalId, 
            T.CumulativeIntervalNumber AS CumulativeInterval_CumulativeIntervalNumber, 
            T.PacketCount AS CumulativeInterval_PacketCount, 
            T.Marked AS CumulativeInterval_Marked, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.CumulativeInterval AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.CumulativeProbabilityDistribution.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CumulativeProbabilityDistribution
        [COWE.PacketsTestModel.Store.CumulativeProbabilityDistribution](T1.CumulativeProbabilityDistribution_CumulativeProbabilityDistributionId, T1.CumulativeProbabilityDistribution_Interval, T1.CumulativeProbabilityDistribution_Probability, T1.CumulativeProbabilityDistribution_CaptureState)
    FROM (
        SELECT 
            T.CumulativeProbabilityDistributionId AS CumulativeProbabilityDistribution_CumulativeProbabilityDistributionId, 
            T.Interval AS CumulativeProbabilityDistribution_Interval, 
            T.Probability AS CumulativeProbabilityDistribution_Probability, 
            T.CaptureState AS CumulativeProbabilityDistribution_CaptureState, 
            True AS _from0
        FROM PacketsTestEntities.CumulativeProbabilityDistributions AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.CumulativeProbabilityDistributions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CumulativeProbabilityDistributions
        [COWE.PacketsTestModel.CumulativeProbabilityDistribution](T1.CumulativeProbabilityDistribution_CumulativeProbabilityDistributionId, T1.CumulativeProbabilityDistribution_Interval, T1.CumulativeProbabilityDistribution_Probability, T1.CumulativeProbabilityDistribution_CaptureState)
    FROM (
        SELECT 
            T.CumulativeProbabilityDistributionId AS CumulativeProbabilityDistribution_CumulativeProbabilityDistributionId, 
            T.Interval AS CumulativeProbabilityDistribution_Interval, 
            T.Probability AS CumulativeProbabilityDistribution_Probability, 
            T.CaptureState AS CumulativeProbabilityDistribution_CaptureState, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.CumulativeProbabilityDistribution AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.DisplayStatistic.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DisplayStatistic
        [COWE.PacketsTestModel.Store.DisplayStatistic](T1.DisplayStatistic_DisplayStatisticId, T1.DisplayStatistic_IntervalCount, T1.DisplayStatistic_TrimmedIntervalCount, T1.DisplayStatistic_MeanPacketsPerInterval, T1.DisplayStatistic_StandardDeviation, T1.DisplayStatistic_MinPacketsPerInterval, T1.DisplayStatistic_MaxPacketsPerInterval, T1.DisplayStatistic_MeanOfMeans, T1.DisplayStatistic_MeanOfMeansStandardDeviation, T1.DisplayStatistic_Marked, T1.DisplayStatistic_BatchType)
    FROM (
        SELECT 
            T.DisplayStatisticId AS DisplayStatistic_DisplayStatisticId, 
            T.IntervalCount AS DisplayStatistic_IntervalCount, 
            T.TrimmedIntervalCount AS DisplayStatistic_TrimmedIntervalCount, 
            T.MeanPacketsPerInterval AS DisplayStatistic_MeanPacketsPerInterval, 
            T.StandardDeviation AS DisplayStatistic_StandardDeviation, 
            T.MinPacketsPerInterval AS DisplayStatistic_MinPacketsPerInterval, 
            T.MaxPacketsPerInterval AS DisplayStatistic_MaxPacketsPerInterval, 
            T.MeanOfMeans AS DisplayStatistic_MeanOfMeans, 
            T.MeanOfMeansStandardDeviation AS DisplayStatistic_MeanOfMeansStandardDeviation, 
            T.Marked AS DisplayStatistic_Marked, 
            T.BatchType AS DisplayStatistic_BatchType, 
            True AS _from0
        FROM PacketsTestEntities.DisplayStatistics AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.DisplayStatistics.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DisplayStatistics
        [COWE.PacketsTestModel.DisplayStatistic](T1.DisplayStatistic_DisplayStatisticId, T1.DisplayStatistic_IntervalCount, T1.DisplayStatistic_TrimmedIntervalCount, T1.DisplayStatistic_MeanPacketsPerInterval, T1.DisplayStatistic_StandardDeviation, T1.DisplayStatistic_MinPacketsPerInterval, T1.DisplayStatistic_MaxPacketsPerInterval, T1.DisplayStatistic_MeanOfMeans, T1.DisplayStatistic_MeanOfMeansStandardDeviation, T1.DisplayStatistic_Marked, T1.DisplayStatistic_BatchType)
    FROM (
        SELECT 
            T.DisplayStatisticId AS DisplayStatistic_DisplayStatisticId, 
            T.IntervalCount AS DisplayStatistic_IntervalCount, 
            T.TrimmedIntervalCount AS DisplayStatistic_TrimmedIntervalCount, 
            T.MeanPacketsPerInterval AS DisplayStatistic_MeanPacketsPerInterval, 
            T.StandardDeviation AS DisplayStatistic_StandardDeviation, 
            T.MinPacketsPerInterval AS DisplayStatistic_MinPacketsPerInterval, 
            T.MaxPacketsPerInterval AS DisplayStatistic_MaxPacketsPerInterval, 
            T.MeanOfMeans AS DisplayStatistic_MeanOfMeans, 
            T.MeanOfMeansStandardDeviation AS DisplayStatistic_MeanOfMeansStandardDeviation, 
            T.Marked AS DisplayStatistic_Marked, 
            T.BatchType AS DisplayStatistic_BatchType, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.DisplayStatistic AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for COWEPacketsTestModelStoreContainer.HypothesisTest.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HypothesisTest
        [COWE.PacketsTestModel.Store.HypothesisTest](T1.HypothesisTest_HypothesisTestId, T1.HypothesisTest_MeanOfMeansVariance, T1.HypothesisTest_MeansVarianceStandardDeviation, T1.HypothesisTest_KsStatistic, T1.HypothesisTest_MaxCpdVariance, T1.HypothesisTest_MeansTestResult, T1.HypothesisTest_KsTestResult, T1.HypothesisTest_HasValues)
    FROM (
        SELECT 
            T.HypothesisTestId AS HypothesisTest_HypothesisTestId, 
            T.MeanOfMeansVariance AS HypothesisTest_MeanOfMeansVariance, 
            T.MeansVarianceStandardDeviation AS HypothesisTest_MeansVarianceStandardDeviation, 
            T.KsStatistic AS HypothesisTest_KsStatistic, 
            T.MaxCpdVariance AS HypothesisTest_MaxCpdVariance, 
            T.MeansTestResult AS HypothesisTest_MeansTestResult, 
            T.KsTestResult AS HypothesisTest_KsTestResult, 
            T.HasValues AS HypothesisTest_HasValues, 
            True AS _from0
        FROM PacketsTestEntities.HypothesisTests AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for PacketsTestEntities.HypothesisTests.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HypothesisTests
        [COWE.PacketsTestModel.HypothesisTest](T1.HypothesisTest_HypothesisTestId, T1.HypothesisTest_MeanOfMeansVariance, T1.HypothesisTest_MeansVarianceStandardDeviation, T1.HypothesisTest_KsStatistic, T1.HypothesisTest_MaxCpdVariance, T1.HypothesisTest_MeansTestResult, T1.HypothesisTest_KsTestResult, T1.HypothesisTest_HasValues)
    FROM (
        SELECT 
            T.HypothesisTestId AS HypothesisTest_HypothesisTestId, 
            T.MeanOfMeansVariance AS HypothesisTest_MeanOfMeansVariance, 
            T.MeansVarianceStandardDeviation AS HypothesisTest_MeansVarianceStandardDeviation, 
            T.KsStatistic AS HypothesisTest_KsStatistic, 
            T.MaxCpdVariance AS HypothesisTest_MaxCpdVariance, 
            T.MeansTestResult AS HypothesisTest_MeansTestResult, 
            T.KsTestResult AS HypothesisTest_KsTestResult, 
            T.HasValues AS HypothesisTest_HasValues, 
            True AS _from0
        FROM COWEPacketsTestModelStoreContainer.HypothesisTest AS T
    ) AS T1");
        }
    }
}
